- name: task level variables
  hosts: local
  connection: local
  vars:
    COURSE: DevSecOps with AWS
    DURATION: 10 HRS
    TRAINER: Siva Kumar
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"

  - name: print course information again
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"